<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Reference\Entity\ProductGroup'           => __DIR__ . '/src/Reference/Entity/ProductGroup.php',
    'Reference\Entity\ReferenceList'          => __DIR__ . '/src/Reference/Entity/ReferenceList.php',
    'Reference\Factory\ProductGroupModel'     => __DIR__ . '/src/Reference/Factory/ProductGroupModel.php',
    'Reference\Factory\ReferenceModelFactory' => __DIR__ . '/src/Reference/Factory/ReferenceModelFactory.php',
    'Reference\Model\AbstractReferenceModel'  => __DIR__ . '/src/Reference/Model/AbstractReferenceModel.php',
    'Reference\Model\ProductGroupModel'       => __DIR__ . '/src/Reference/Model/ProductGroupModel.php',
    'Reference\Model\ReferenceModel'          => __DIR__ . '/src/Reference/Model/ReferenceModel.php',
    'Reference\Module'                        => __DIR__ . '/Module.php',
    'Reference\Repository\ProductGroup'       => __DIR__ . '/src/Reference/Repository/ProductGroup.php',
);
