FORMAT: 1A
HOST: http://cargo.zfprojects.info/api

# Cargo API
API предназначено для взаимодействием с учетно-информационной системой транспортной логистики "Карго"

# Cargo API Root [/]
Корень API.

Этот ресурс определяет список доступных в данном API ресурсов.

## Список ресурсов [GET]

+ Response 200 (application/hal+json)

    + Body

            {
                "_links": {
                    "self": { "href": "/api" },
                    "accounts": { "href": "/api/accounts", "templated": true }
                    "profiles": { "href": "/api/profiles", "templated": true }
                }
            }

# Account [/accounts{/uuid}]
Детальная информация об аккаунте

+ Parameters
    + uuid (required, string, `4e178674-4f93-11e3-90b7-080027ab4d7b`) ... Уникальный идентификатор, указывающий на конкретный аккаунт


+ Model (application/hal+json)

    HAL+JSON предсавление сущности *Аккаунт*.

    + Body

            {
                "_links": {
                    "self": { "href": "/api/accounts/cb37dcb8-4f92-11e3-827c-080027ab4d7b" }
                },
                "account_uuid": "cb37dcb8-4f92-11e3-827c-080027ab4d7b",
                "created_at": "2013-04-14T02:15:15Z",
                "title": "Веста",
                "_embedded": {
                    "companies": [
                        {
                            "_links": {
                                "self": {
                                    "href": "/api/accounts/cb37dcb8-4f92-11e3-827c-080027ab4d7b/companies/0f7e27b4-4f94-11e3-aa00-080027ab4d7b"
                                }
                            },
                            "company_uuid": "0f7e27b4-4f94-11e3-aa00-080027ab4d7b",
                            "title": "ООО Озерки"
                        },
                        {
                            "_links": {
                                "self": {
                                    "href": "/api/accounts/cb37dcb8-4f92-11e3-827c-080027ab4d7b/companies/10af631e-4f94-11e3-8698-080027ab4d7b"
                                }
                            },
                            "company_uuid": "10af631e-4f94-11e3-8698-080027ab4d7b",
                            "title": "ЗАО Ручеек"
                        }
                    ]
                }
            }

## Получить данные аккаунта [GET]
+ Response 200 (application/json)

    [Account][]

## Удаление аккаунта [DELETE]
+ Response 204

## Изменение аккаунта [PATCH]
Изменение данных аккаунта. Будут изменены только те свойства, которые указаны в запросе

+ Request (application/json)

        {
            "title": "Ручеек"
        }

+ Response 204

# Accounts Collection [/accounts]
Список доступных аккаунтов.

Этот ресурс имеет следующий атрибут:

- total

Дополнительно в него **внедряются** *Accounts Resource*

+ Model (application/hal+json)

    HAL+JSON предсавление списка аккаунтов.

    + Body

            {
                "_links": {
                    "self": { "href": "/api/accounts" }
                },
                "_embedded": {
                    "accounts": [
                        {
                            "_links" : {
                                "self": { "href": "/api/accounts/cb37dcb8-4f92-11e3-827c-080027ab4d7b" }
                            },
                            "account_uuid": "cb37dcb8-4f92-11e3-827c-080027ab4d7b",
                            "created_at": "2013-04-14T02:15:15Z",
                            "title": "Веста"
                        },
                        {
                            "_links" : {
                                "self": { "href": "/api/accounts/d59f8dae-4f92-11e3-a070-080027ab4d7b" }
                            },
                            "account_uuid": "d59f8dae-4f92-11e3-a070-080027ab4d7b",
                            "created_at": "2013-05-11T22:04:25Z",
                            "title": "Талосто"
                        }
                    ]
                },
                "total": 2
            }

## Список всех доступных аккаунтов [GET]

+ Response 200

    [Accounts Collection][]

+ Response 404

    + Headers

            Content-Type: application/hal+json

    + Body

            {
                "_links": {
                    "self": { "href": "/api/accounts" }
                },
                "_embedded": {
                    "accounts": [
                    ]
                },
                "total": 0
            }


## Создание нового аккаунта [POST]
Чтобы создать новый аккаунт просто передайте JSON-объект с названием аккаунта в атрибуте *title*.

+ Request (application/json)

        {
            "title": "Тест"
        }

+ Response 201 (application/json)

        {
            "_links" : {
                "self": { "href": "/api/accounts/cb37dcb8-4f92-11e3-827c-080027ab4d7b" }
            },
            "account_uuid": "cb37dcb8-4f92-11e3-827c-080027ab4d7b",
            "created_at": "2013-04-14T02:15:15Z",
            "title": "Веста"
        }


# Account Company [/accounts/{account_uuid}/companies/{company_uuid}]
Юридическое лицо, управляемое в рамках аккаунта

+ Parameters

    + uuid (required, string, `4e178674-4f93-11e3-90b7-080027ab4d7b`) ... Уникальный идентификатор аккаунта
    + company_uuid (required, string, `10af631e-4f94-11e3-8698-080027ab4d7b`) ... Уникальный идентификатор компании

+ Model (application/hal+json)

    HAL+JSON representation of Account Company.

    + Body

            {
                "_links": {
                    "self": { "href": "/api/accounts/4e178674-4f93-11e3-90b7-080027ab4d7b/companies/10af631e-4f94-11e3-8698-080027ab4d7b" },
                    "company": { "href": "/api/companies/10af631e-4f94-11e3-8698-080027ab4d7b" },
                },
                "shortName": "ЗАО Ручеек"
            }

## Исключить компанию из аккаунта [DELETE]

+ Response 204

# Account Companies [/accounts/{account_uuid}/companies]
Юридические лица, принадлежащие аккаунту

+ Parameters

    + account_uuid (required, string, `4e178674-4f93-11e3-90b7-080027ab4d7b`) ... Уникальный идентификатор аккаунта

+ Model (application/hal+json)

    HAL+JSON representation of Account Company.

    + Body

            {
                "_links": {
                    "self": { "href": "/api/accounts/4e178674-4f93-11e3-90b7-080027ab4d7b/companies/10af631e-4f94-11e3-8698-080027ab4d7b" },
                    "companies": [
                        { "href": "/api/companies/10af631e-4f94-11e3-8698-080027ab4d7b" },
                        { "href": "/api/companies/5e292178-523e-11e3-a4e4-080027ab4d7b" }
                    ]
                },
                "_embedded": {
                    "companies": [
                        {
                            "company_uuid": "10af631e-4f94-11e3-8698-080027ab4d7b",
                            "short": "ЗАО Ручеек"
                        },
                        {
                            "company_uuid": "5e292178-523e-11e3-a4e4-080027ab4d7b",
                            "short": "ОАО Озерко"
                        }
                    ]
                }
            }

## Добавить юридическое лицо в аккаунт [POST]
Добавляет новое юридическое лицо в аккаунт **uuid**

+ Request (application/json)

            {
                "name": "", // Полное наименование юридического лица
                "short": "", // Краткое наименование юридического лица
                "property": "", // Вид собственности
                "inn": "", // ИНН
                "ogrn": "", // ОГРН
                "kpp": "", // КПП
                "tax": {
                    "agency_number": "", // Номер налоговой
                    "date_accounting": "", // Дата постановки на учет
                    "date_registration": "", // Дата регистрации
                    "registration_agency_number": "", // Номер налоговой, где проходила регистрация
                    "system": "", // Вид системы налогового учета
                    "rate": 35, // Процентная ставка налога
                },
                "addresses": [ // Адреса
                    {
                        "title": "Центральный офис",
                        "city": "Москва",
                        "street": "",
                        "build": "",
                        "house": "",
                        "office": ""
                    }
                ],
                "contacts": [ // Контакты
                    {
                        "phone": "",
                        "name": "",
                        "position": ""
                    }
                ],
                "forming_method": "", // Способ образования
                "capital": "", // Размер уставного капитала
                "founder_count": 10, // Количество учредителей
                "founders": [], // Учредители
                "authorized_persons": [], // Уполномоченные лица
                "okved": [], // Коды ОКВЭД
                "pfr": {
                    "number": "", // Номер ПФР
                    "date_registration": "", // Дата постановки в ПФР
                    "insurance": "" // Номер страхования в ПФР
                },
                "fms": {
                    "number": "", // Номер ФМС
                    "date_registration": "", // Дата постановки в ФМС
                    "insurance": "" // Номер страхования ФМС
                },
                "licenses": [], // Лицензии
                "applicants": [], // Заявители при регистрации
                "accounts": [ // Банковские реквизиты
                    {
                        "bank": "", // Название банка
                        "account": "", // расчетный счет
                        "corresp": "", // Корреспондентский счет
                        "bik": "", // БИК
                    }
                ],
                "persons": { // Ссылки на других ответственных лиц с указанием области ответственности
                    {
                        "position": "accountant",
                        "name": "Иванов И.И."
                    },
                    {
                        "position": "ceo",
                        "name": "Петров П.П."
                    }
                },
                "sites": [], // Ссылки на сайты
            }

+ Response 204



# Profile [/profiles/{uuid}]
Детальная информация о профиле пользователя

+ Parameters
    + uuid (required, string, `5e292178-523e-11e3-a4e4-080027ab4d7b`) ... Уникальный идентификатор, указывающий на конкретного пользователя


+ Model (application/hal+json)

    HAL+JSON предсавление сущности *Пользователь*.

    + Body

            {
                "_links": {
                    "self": { "href": "/api/profile/5e292178-523e-11e3-a4e4-080027ab4d7b" }
                },
                "id": "5e292178-523e-11e3-a4e4-080027ab4d7b",
                "created_at": "2013-04-14T02:15:15Z",
                "name": {
                    "first": "Иван",
                    "second": "Иванович",
                    "last": "Иванов",
                    "short": "Иванов И.И."
                },
                "email": "",
                "docs": {
                    "type": "pasport",
                    "serial": "",
                    "number": "",
                    "issued": {
                        "agency": "",
                        "date": "",
                        "code": ""
                    },
                    "birth": {
                        "date": "",
                        "place": ""
                    },
                    "registration": {
                        "type": "",
                        "address": "",
                        "date": ""
                    }
                },
                "snils": "",
                "inn": "",
                "phone": [
                    "+7 926 543-5400"
                ],
                "site": [],
                "avatar": "",
                "sign": {
                    "valid_to": "",
                    "qualification": "",
                    "credentials": ""
                },
                "social": {
                    "mailru": "",
                    "yandex": "",
                    "vk": "",
                    "ok": "",
                    "google": "",
                    "fb": "",
                    "linkedin": ""
                }
            }

## Получить данные профиля [GET]
+ Response 200 (application/json)

    [Profile][]

## Удаление профиля [DELETE]
+ Response 204

## Изменение данных профиля [PATCH]
Изменение данных аккаунта. Будут изменены только те свойства, которые указаны в запросе

+ Request (application/json)

        {
            "name": {
                "short": "Иванов И."
            }
        }

+ Response 204

# Company [/companies/{uuid}]
Подробная информация о юридическом лице

+ Parameters
    + uuid (required, string, `5e292178-523e-11e3-a4e4-080027ab4d7b`) ... Уникальный идентификатор юридического лица


+ Model (application/hal+json)

    HAL+JSON предсавление сущности *Юридическое лицо*.

    + Body

            {
                "_links": {
                    "self": { "href": "/api/companies/5e292178-523e-11e3-a4e4-080027ab4d7b" },
                    "documents": {
                        "charter": { "href": "/files/5e292178-523e-11e3-a4e4-080027ab4d7b/carter.pdf" }, // Ссылка на файлы устава
                        "egrul": { "href": "/files/5e292178-523e-11e3-a4e4-080027ab4d7b/egrul.pdf" }, // Ссылка на файлы выписки из ЕГРЮЛ/ЕГРЮИП
                        // ... прочие документы
                    }
                },
                "uuid": "5e292178-523e-11e3-a4e4-080027ab4d7b",
                "created": "1387302682", // Дата создания записи о юридическом лице в системе
                "name": "", // Полное наименование юридического лица
                "short": "", // Краткое наименование юридического лица
                "property": "", // Вид собственности
                "inn": "", // ИНН
                "ogrn": "", // ОГРН
                "kpp": "", // КПП
                "tax": {
                    "agency_number": "", // Номер налоговой
                    "date_accounting": "", // Дата постановки на учет
                    "date_registration": "", // Дата регистрации
                    "registration_agency_number": "", // Номер налоговой, где проходила регистрация
                    "system": "", // Вид системы налогового учета
                    "rate": 35, // Процентная ставка налога
                },
                "addresses": [ // Адреса
                    {
                        "title": "Центральный офис",
                        "city": "Москва",
                        "street": ""
                        "house": "",
                        "office": ""
                    }
                ],
                "contacts": [
                    {
                        "phone": "",
                        "name": "",
                        "position": ""
                    }
                ], // Контакты
                "forming_method": "", // Способ образования
                "capital": "", // Размер уставного капитала
                "founder_count": 10, // Количество учредителей
                "founders": [], // Учредители
                "authorized_persons": [], // Уполномоченные лица
                "okved": [], // Коды ОКВЭД
                "pfr": {
                    "number": "", // Номер ПФР
                    "date_registration": "", // Дата постановки в ПФР
                    "insurance": "" // Номер страхования в ПФР
                },
                "fms": {
                    "number": "", // Номер ФМС
                    "date_registration": "", // Дата постановки в ФМС
                    "insurance": "" // Номер страхования ФМС
                },
                "licenses": [], // Лицензии
                "applicants": [], // Заявители при регистрации
                "accounts": [ // Банковские реквизиты
                    {
                        "bank": "", // Название банка
                        "account": "", // расчетный счет
                        "corresp": "", // Корреспондентский счет
                        "bik": "", // БИК
                    }
                ],
                "persons": { // Ссылки на других ответственных лиц с указанием области ответственности
                    {
                        "position": "accountant",
                        "name": "Иванов И.И."
                    },
                    {
                        "position": "ceo",
                        "name": "Петров П.П."
                    }
                },
                "sites": [], // Ссылки на сайты
            }

## Получить данные о юридическом лице [GET]
+ Response 200 (application/json)

    [Company][]

## Удаление юридического лица [DELETE]
+ Response 204

## Изменение данных юридического лица [PATCH]
Изменение данных о юридическом лице. Будут изменены только те свойства, которые указаны в запросе

+ Request (application/json)

        {
            "name": {
                "short": "Иванов И."
            }
        }

+ Response 204

# Companies list [/companies]
Юридические лица

+ Model (application/hal+json)

    HAL+JSON предсавление списка сущностей *Юридическое лицо*.

    + Body

            {
                "_links": {
                    "self": { "href": "/api/companies" }
                },
                "_embedded": {
                    "companies": [
                        {
                            "_links": {
                                "self": { "href": "/api/companies/5e292178-523e-11e3-a4e4-080027ab4d7b" },
                            },
                            "uuid": "5e292178-523e-11e3-a4e4-080027ab4d7b",
                            "created": "1387302682", // Дата создания записи о юридическом лице в системе
                            "name": "", // Полное наименование юридического лица
                            "short": "", // Краткое наименование юридического лица
                            "property": "", // Вид собственности
                            "inn": "", // ИНН
                            "ogrn": "", // ОГРН
                            "kpp": "", // КПП
                            "tax": {
                                "agency_number": "", // Номер налоговой
                                "date_accounting": "", // Дата постановки на учет
                                "date_registration": "", // Дата регистрации
                                "registration_agency_number": "", // Номер налоговой, где проходила регистрация
                                "system": "", // Вид системы налогового учета
                                "rate": 35, // Процентная ставка налога
                            },
                            "addresses": [ // Адреса
                                {
                                    "title": "Центральный офис",
                                    "city": "Москва",
                                    "street": ""
                                    "house": "",
                                    "office": ""
                                }
                            ],
                            "contacts": [
                                {
                                    "phone": "",
                                    "name": "",
                                    "position": ""
                                }
                            ], // Контакты
                            "forming_method": "", // Способ образования
                            "capital": "", // Размер уставного капитала
                            "founder_count": 10, // Количество учредителей
                            "founders": [], // Учредители
                            "authorized_persons": [], // Уполномоченные лица
                            "okved": [], // Коды ОКВЭД
                            "pfr": {
                                "number": "", // Номер ПФР
                                "date_registration": "", // Дата постановки в ПФР
                                "insurance": "" // Номер страхования в ПФР
                            },
                            "fms": {
                                "number": "", // Номер ФМС
                                "date_registration": "", // Дата постановки в ФМС
                                "insurance": "" // Номер страхования ФМС
                            },
                            "licenses": [], // Лицензии
                            "applicants": [], // Заявители при регистрации
                            "accounts": [ // Банковские реквизиты
                                {
                                    "bank": "", // Название банка
                                    "account": "", // расчетный счет
                                    "corresp": "", // Корреспондентский счет
                                    "bik": "", // БИК
                                }
                            ],
                            "persons": { // Ссылки на других ответственных лиц с указанием области ответственности
                                {
                                    "position": "accountant",
                                    "name": "Иванов И.И."
                                },
                                {
                                    "position": "ceo",
                                    "name": "Петров П.П."
                                }
                            },
                            "sites": [], // Ссылки на сайты
                        }
                    ]
                },
            }

## Поличить список юридических лиц [GET]
Возвращает список юридических лиц, зарегистрированнх в системе

+ Response 200

    [Companies list][]


## Добавить юридическое лицо в аккаунт [POST]
Добавляет новое юридическое лицо в аккаунт **uuid**

+ Request (application/json)

            {
                "name": "", // Полное наименование юридического лица
                "short": "", // Краткое наименование юридического лица
                "property": "", // Вид собственности
                "inn": "", // ИНН
                "ogrn": "", // ОГРН
                "kpp": "", // КПП
                "tax": {
                    "agency_number": "", // Номер налоговой
                    "date_accounting": "", // Дата постановки на учет
                    "date_registration": "", // Дата регистрации
                    "registration_agency_number": "", // Номер налоговой, где проходила регистрация
                    "system": "", // Вид системы налогового учета
                    "rate": 35, // Процентная ставка налога
                },
                "addresses": [ // Адреса
                    {
                        "title": "Центральный офис",
                        "city": "Москва",
                        "street": "",
                        "build": "",
                        "house": "",
                        "office": ""
                    }
                ],
                "contacts": [ // Контакты
                    {
                        "phone": "",
                        "name": "",
                        "position": ""
                    }
                ],
                "forming_method": "", // Способ образования
                "capital": "", // Размер уставного капитала
                "founder_count": 10, // Количество учредителей
                "founders": [], // Учредители
                "authorized_persons": [], // Уполномоченные лица
                "okved": [], // Коды ОКВЭД
                "pfr": {
                    "number": "", // Номер ПФР
                    "date_registration": "", // Дата постановки в ПФР
                    "insurance": "" // Номер страхования в ПФР
                },
                "fms": {
                    "number": "", // Номер ФМС
                    "date_registration": "", // Дата постановки в ФМС
                    "insurance": "" // Номер страхования ФМС
                },
                "licenses": [], // Лицензии
                "applicants": [], // Заявители при регистрации
                "accounts": [ // Банковские реквизиты
                    {
                        "bank": "", // Название банка
                        "account": "", // расчетный счет
                        "corresp": "", // Корреспондентский счет
                        "bik": "", // БИК
                    }
                ],
                "persons": { // Ссылки на других ответственных лиц с указанием области ответственности
                    {
                        "position": "accountant",
                        "name": "Иванов И.И."
                    },
                    {
                        "position": "ceo",
                        "name": "Петров П.П."
                    }
                },
                "sites": [], // Ссылки на сайты
            }

+ Response 201

# Place [/places/{uuid}]
Подробная информация о Пункте

+ Parameters
    + uuid (required, string, `5e292178-523e-11e3-a4e4-080027ab4d7b`) ... Уникальный идентификатор пункта


+ Model (application/hal+json)

    HAL+JSON предсавление сущности *Пункт*.

    + Body

            {
                "_links": {
                    "self": { "href": "/api/places/5e292178-523e-11e3-a4e4-080027ab4d7b" },
                },
                "uuid": "5e292178-523e-11e3-a4e4-080027ab4d7b", // Идентификатор пункта
                "name": "", // Название (наименование пункта)
                "company": { // Владелец (юр лицо)
                    "uuid": "c14bfc17646343b4afc037fb3c8c5391", // идентификатор компании
                    "name": "" // Название компании
                },
                "purpose" = [], // Назначения пункта - может быть несколько (офис, отгрузки, доставки, хранения др.)
                "address": { // Адрес пункта
                    "country": "Российская Федерация", // страна
                    "city": "Москва", // город
                    "street": "Веневская, ул", // улица
                    "house": "6", // дом
                    "building": "", // корпус/строение
                    "floor": "", // этаж
                    "number": "" // номер квартиры/офиса
                },
                "contacts": [], // Контакты
                "operationTime": "", // Время работы пункта
                "coordinates": "", // Координаты
                "staff": [], // Физ лица (сотрудники юр лица), находящиеся непосредственно на данном пункте
                "active": 1, // Признак активности (если активен, то появляется в выпадающих списках)
                "electronicWorkflow": 0, // Признак использования электронного документоборота
                "note": "", // Дополнительная информация
                "rating": 3, // Рейтинг пункта
                "created": "1387302682", // Дата создания записи
                "deleted": null, // Дата удаления записи
                "creator": { // Пользователь, создавший запись
                    "uuid": "3a53e466-7662-11e3-b84b-080027ab4d7b", // идентификатор пользователя
                    "name": "" // ФИО пользователя
                },
                "acceptor": { // Пользователь, акцептовавший запись
                    "uuid": "421c299c-7662-11e3-8d94-080027ab4d7b", // идентификатор пользователя
                    "name": "" // ФИО пользователя
                }
            }

## Запрос данных о пункте [GET]
+ Response 200 (application/json)

    [Place][]

## Удаление пункта [DELETE]
+ Response 204

+ Response 422

## Изменение данных пункта [PATCH]
Изменение данных о пункте. Будут изменены только те свойства, которые указаны в запросе

+ Request (application/json)

        {
            "name": "Пункт номер один"
        }

+ Response 204

# Places list [/places]
Список зарегистрированных в системе Пунктов

+ Model (application/hal+json)

    HAL+JSON предсавление списка сущностей *Юридическое лицо*.

    + Body

            {
                "_links": {
                    "self": { "href": "/api/places" }
                },
                "_embedded": {
                    "places": [
                        {
                            "_links": {
                                "self": { "href": "/api/places/5e292178-523e-11e3-a4e4-080027ab4d7b" },
                            },
                            "uuid": "5e292178-523e-11e3-a4e4-080027ab4d7b", // Идентификатор пункта
                            "name": "", // Название (наименование пункта)
                            "company": { // Владелец (юр лицо)
                                "uuid": "c14bfc17646343b4afc037fb3c8c5391", // идентификатор компании
                                "name": "" // Название компании
                            },
                            "purpose" = [], // Назначения пункта - может быть несколько (офис, отгрузки, доставки, хранения др.)
                            "address": { // Адрес пункта
                                "country": "Российская Федерация", // страна
                                "city": "Москва", // город
                                "street": "Веневская, ул", // улица
                                "house": "6", // дом
                                "building": "", // корпус/строение
                                "floor": "", // этаж
                                "number": "" // номер квартиры/офиса
                            },
                            "contacts": [], // Контакты
                            "operationTime": "", // Время работы пункта
                            "coordinates": "", // Координаты
                            "staff": [], // Физ лица (сотрудники юр лица), находящиеся непосредственно на данном пункте
                            "active": 1, // Признак активности (если активен, то появляется в выпадающих списках)
                            "electronicWorkflow": 0, // Признак использования электронного документоборота
                            "note": "", // Дополнительная информация
                            "rating": 3, // Рейтинг пункта
                            "created": "1387302682", // Дата создания записи
                            "deleted": null, // Дата удаления записи
                            "creator": { // Пользователь, создавший запись
                                "uuid": "3a53e466-7662-11e3-b84b-080027ab4d7b", // идентификатор пользователя
                                "name": "" // ФИО пользователя
                            },
                            "acceptor": { // Пользователь, акцептовавший запись
                                "uuid": "421c299c-7662-11e3-8d94-080027ab4d7b", // идентификатор пользователя
                                "name": "" // ФИО пользователя
                            }
                        }
                    ]
                },
            }

## Поличить список пунктов [GET]
Возвращает список пунктов, зарегистрированнх в системе

+ Response 200

    [Places list][]


## Добавить пункт [POST]
Добавляет новый пункт

+ Request (application/json)

            {
                "name": "", // Название (наименование пункта)
                "company": { // Владелец (юр лицо)
                    "uuid": "c14bfc17646343b4afc037fb3c8c5391", // идентификатор компании
                },
                "purpose" = [], // Назначения пункта - может быть несколько (офис, отгрузки, доставки, хранения др.)
                "address": { // Адрес пункта
                    "country": "Российская Федерация", // страна
                    "city": "Москва", // город
                    "street": "Веневская, ул", // улица
                    "house": "6", // дом
                    "building": "", // корпус/строение
                    "floor": "", // этаж
                    "number": "" // номер квартиры/офиса
                },
                "contacts": [], // Контакты
                "operationTime": "", // Время работы пункта
                "coordinates": "", // Координаты
                "staff": [], // Физ лица (сотрудники юр лица), находящиеся непосредственно на данном пункте
                "active": 1, // Признак активности (если активен, то появляется в выпадающих списках)
                "electronicWorkflow": 0, // Признак использования электронного документоборота
                "note": "", // Дополнительная информация
                "rating": 3, // Рейтинг пункта
            }

+ Response 201

# Product Group Reference [/ref/product-group/{/code}]
Справочник продуктовых групп

Атрибуты ресурса:

- **code** - код продуктовой группы
- **title** - название продуктовой группы

+ Parameters
    + code (required, string, `milk`) ... Код продуктовой группы


+ Model (application/hal+json)

    HAL+JSON предсавление сущности *Справочник продуктовых групп*.

    + Body

            {
                "_links": {
                    "self": { "href": "/api/ref/product-group/milk" },
                    "list": { "href": "/api/ref/product-group" }
                },
                "code": "milk",
                "title": "Молочные продукты",
            }

## Получить продуктовую группу [GET]
+ Response 200 (application/hal+json)

    [Product Group Reference][]

## Удаление продуктовой группы [DELETE]
+ Response 204

# Product Group Reference Collection [/ref/product-group]
Список продуктовых групп

Атрибуты ресурса:

- **total** - количество продуктовых групп

+ Model (application/hal+json)

    HAL+JSON предсавление списка аккаунтов.

    + Body

            {
                "_links": {
                    "self": { "href": "/api/ref/product-group" }
                },
                "_embedded": {
                    "groups": [
                        {
                            "_links": {
                                "self": { "href": "/api/ref/product-group/fish" },
                                "list": { "href": "/api/ref/product-group" }
                            },
                            "code": "fish",
                            "title": "Рыба",
                        },
                        {
                            "_links": {
                                "self": { "href": "/api/ref/product-group/milk" },
                                "list": { "href": "/api/ref/product-group" }
                            },
                            "code": "milk",
                            "title": "Молочные продукты",
                        },
                        {
                            "_links": {
                                "self": { "href": "/api/ref/product-group/food" },
                                "list": { "href": "/api/ref/product-group" }
                            },
                            "code": "food",
                            "title": "Продукты питания",
                        }
                    ]
                },
                "total": 3
            }

## Список всех продуктовых групп [GET]

+ Response 200

    [Product Group Reference Collection][]

+ Response 404 (application/hal+json)

    + Body

            {
                "_links": {
                    "self": { "href": "/api/ref/product-group" }
                },
                "_embedded": {
                    "groups": [
                    ]
                },
                "total": 0
            }

## Создание новой продуктовой группы [POST]
Для создания новой продуктовой группы нужно передать json-объект с кодом продуктовой группы и её названием.

+ Request (application/json)

            {
                "code": "milk",
                "title": "Молочные продукты",
            }

+ Response 201

## Изменение продуктовой группы [PUT]
Изменение данных продуктовой группы. Если группа с таким кодом существует, то она будет изменена, иначе будет создана новая.

+ Request (application/json)

        {
            "code": "milk",
            "title": "Молочные продукты",
        }

+ Response 202

+ Response 201

# Company import service [/service/import/company]
Сервис для импорта юридических лиц из систем "Онлайн". Необходим для синхронизации списка юридических лиц между Cargo и системами "Онлайн".


## Выполнение импорта юридических лиц [GET]

+ Response 200 (application/hal+json)

        {
            "_links": {
                "self": { "href": "/api/service/import/company" }
            },
            "status": "success",
            "stat": {
                "processed": 10,
                "new": 3,
                "changed": 2,
                "exists": 5
            }
        }

+ Response 400 (application/hal+json)

        {
            "_links": {
                "self": { "href": "/api/service/import/company" }
            },
            "status": "fail",
            "reason": "Сообщение об ошибке"
        }


# Link companies with external records [/service/import/company-intersect]
Сервис для связи юридических лиц, импортированных из систем "Онлайн", с юридическими лицами Cargo.

## Запрос списка импортированных юридических лиц [GET]

+ Response 200 (application/hal+json)

        {
            "_links": {
                "self": { "href": "/api/service/import/company-intersect" }
            },
            "companies": [
                {
                    "code": "vesta-123",
                    "id": 123,
                    "source": "vesta",
                    "name": "ООО Талосто",
                    "link": "5e292178-523e-11e3-a4e4-080027ab4d7b" // uuid связанной компании
                }
            ]
        }

## Добавление связи между юридическими лицами [POST]

+ Request (application/json)

        {
            "source": "vesta",
            "id": 123,
            "company": "5e292178-523e-11e3-a4e4-080027ab4d7b"
        }

+ Response 201

        {
            "_links": {
                "self": { "href": "/api/service/import/company-intersect" }
            },
            "companies": [
                {
                    "code": "vesta-123",
                    "id": 123,
                    "source": "vesta",
                    "name": "ООО Талосто",
                    "link": "5e292178-523e-11e3-a4e4-080027ab4d7b" // uuid связанной компании
                }
            ]
        }

# Modify companies link with external records [/service/import/company-intersect{/source-id}]
Ресурс для изменения связей между юридическими лицами, импортированными из систем "Онлайн", и юридическими лицами Cargo.

+ Parameters
    + source (required, string, `vesta-123`) ... Идентификатор импортированной компании. Состоит из кода внешней системы (Онлайн-а) и идентификатора компании в той системе, из которой была импортирована запись

## Удаление связи между юридическими лицами [DELETE]

+ Response 204

+ Response 422


# Place import service [/service/import/place]
Ресурс для импорта **пунктов доставки**, **складов**, **офисов** из систем "Онлайн". Необходим для синхронизации списка **пунктов** между Cargo и системами "Онлайн".

## Выполнение импорта списка пунктов доставки [GET]

+ Response 200 (application/hal+json)

        {
            "_links": {
                "self": { "href": "/api/service/import/place" }
            },
            "status": "success",
            "stat": {
                "processed": 10,
                "new": 3,
                "changed": 2,
                "exists": 5
            }
        }

+ Response 422 (application/hal+json)

        {
            "_links": {
                "self": { "href": "/api/service/import/place" }
            },
            "status": "fail",
            "reason": "Сообщение об ошибке"
        }

# Link places with external records [/service/import/place-intersect]
Сервис для связи юридических лиц, импортированных из систем "Онлайн", с юридическими лицами Cargo.

## Запрос списка импортированных пунктов [GET]

+ Response 200 (application/hal+json)

        {
            "_links": {
                "self": { "href": "/api/service/import/place-intersect" }
            },
            "_embedded": {
                "places": [
                    {
                        "id": 123,
                        "source": "vesta",
                        "name": "Вторая нагатиская",
                        "type": "dp", // dp - пункт доставки / wh - склад / office - офис
                        "link": "5e292178-523e-11e3-a4e4-080027ab4d7b" // uuid связанной компании
                        "_links": {
                            "self": {
                                'href' => '/api/service/import/place-intersect/vesta-dp-123'
                            }
                        }
                    }
                ]
            }
        }

## Добавление связи между пунктами [POST]

+ Request (application/json)

        {
            "source": "vesta",
            "id": 123,
            "type": "dp",
            "place": "5e292178-523e-11e3-a4e4-080027ab4d7b"
        }

+ Response 202

# Modify places link with external records [/service/import/place-intersect{/source-type-id}]
Ресурс для изменения связей между пунктами, импортированными из систем "Онлайн", и пунктами Cargo.

+ Parameters
    + source (required, string, `vesta-dp-123`) ... Идентификатор импортированного пункта. Состоит из кода внешней системы (Онлайн-а), типа пункта (ПД или склад) и идентификатора пункта в той системе, из которой была импортирована запись

## Удаление связи между пунктами [DELETE]

+ Response 204

+ Response 422
