<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'QueryBuilder\Factory\QueryBuilderModelFactory' => __DIR__ . '/src/QueryBuilder/Factory/QueryBuilderModelFactory.php',
    'QueryBuilder\Model\QueryBuilderModel'          => __DIR__ . '/src/QueryBuilder/Model/QueryBuilderModel.php',
    'QueryBuilder\Module'                           => __DIR__ . '/Module.php',
);
