<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cargo\Entity\Cargo'              => __DIR__ . '/src/Cargo/Entity/Cargo.php',
    'Cargo\Factory\CargoModelFactory' => __DIR__ . '/src/Cargo/Factory/CargoModelFactory.php',
    'Cargo\Model\CargoModel'          => __DIR__ . '/src/Cargo/Model/CargoModel.php',
    'Cargo\Module'                    => __DIR__ . '/Module.php',
);
