<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ExtService\Entity\ExternalCompany'                       => __DIR__ . '/src/ExtService/Entity/ExternalCompany.php',
    'ExtService\Entity\ExternalPunct'                         => __DIR__ . '/src/ExtService/Entity/ExternalPunct.php',
    'ExtService\Factory\ExternalCompanyImportModelFactory'    => __DIR__ . '/src/ExtService/Factory/ExternalCompanyImportModelFactory.php',
    'ExtService\Factory\ExternalCompanyIntersectModelFactory' => __DIR__ . '/src/ExtService/Factory/ExternalCompanyIntersectModelFactory.php',
    'ExtService\Factory\ExternalCompanyModelFactory'          => __DIR__ . '/src/ExtService/Factory/ExternalCompanyModelFactory.php',
    'ExtService\Factory\ExternalPunctImportModelFactory'      => __DIR__ . '/src/ExtService/Factory/ExternalPunctImportModelFactory.php',
    'ExtService\Factory\ExternalPunctIntersectModelFactory'   => __DIR__ . '/src/ExtService/Factory/ExternalPunctIntersectModelFactory.php',
    'ExtService\Factory\ExternalPunctModelFactory'            => __DIR__ . '/src/ExtService/Factory/ExternalPunctModelFactory.php',
    'ExtService\Model\ExternalCompanyImportModel'             => __DIR__ . '/src/ExtService/Model/ExternalCompanyImportModel.php',
    'ExtService\Model\ExternalCompanyIntersectModel'          => __DIR__ . '/src/ExtService/Model/ExternalCompanyIntersectModel.php',
    'ExtService\Model\ExternalCompanyModel'                   => __DIR__ . '/src/ExtService/Model/ExternalCompanyModel.php',
    'ExtService\Model\ExternalPunctImportModel'               => __DIR__ . '/src/ExtService/Model/ExternalPunctImportModel.php',
    'ExtService\Model\ExternalPunctIntersectModel'            => __DIR__ . '/src/ExtService/Model/ExternalPunctIntersectModel.php',
    'ExtService\Model\ExternalPunctModel'                     => __DIR__ . '/src/ExtService/Model/ExternalPunctModel.php',
    'ExtService\Module'                                       => __DIR__ . '/Module.php',
    'ExtService\Provider\OnlineProvider'                      => __DIR__ . '/src/ExtService/Provider/OnlineProvider.php',
    'ExtService\Service\ImportService'                        => __DIR__ . '/src/ExtService/Service/ImportService.php',
);
