<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Account\Entity\Account'                  => __DIR__ . '/src/Account/Entity/Account.php',
    'Account\Entity\Company'                  => __DIR__ . '/src/Account/Entity/Company.php',
    'Account\Entity\CompanyUser'              => __DIR__ . '/src/Account/Entity/CompanyUser.php',
    'Account\Entity\ContractAgents'           => __DIR__ . '/src/Account/Entity/ContractAgents.php',
    'Account\Factory\AccountModelFactory'     => __DIR__ . '/src/Account/Factory/AccountModelFactory.php',
    'Account\Factory\CompanyModelFactory'     => __DIR__ . '/src/Account/Factory/CompanyModelFactory.php',
    'Account\Factory\CompanyUserModelFactory' => __DIR__ . '/src/Account/Factory/CompanyUserModelFactory.php',
    'Account\Model\AccountModel'              => __DIR__ . '/src/Account/Model/AccountModel.php',
    'Account\Model\CompanyModel'              => __DIR__ . '/src/Account/Model/CompanyModel.php',
    'Account\Model\CompanyUserModel'          => __DIR__ . '/src/Account/Model/CompanyUserModel.php',
    'Account\Module'                          => __DIR__ . '/Module.php',
    'Account\Repository\AccountRepository'    => __DIR__ . '/src/Account/Repository/AccountRepository.php',
    'Account\Repository\CompanyRepository'    => __DIR__ . '/src/Account/Repository/CompanyRepository.php',
);
