<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'User\Entity\User'                     => __DIR__ . '/src/User/Entity/User.php',
    'User\Factory\IdentityProviderFactory' => __DIR__ . '/src/User/Factory/IdentityProviderFactory.php',
    'User\Factory\UserModelFactory'        => __DIR__ . '/src/User/Factory/UserModelFactory.php',
    'User\Identity\IdentityProvider'       => __DIR__ . '/src/User/Identity/IdentityProvider.php',
    'User\Model\UserModel'                 => __DIR__ . '/src/User/Model/UserModel.php',
    'User\Module'                          => __DIR__ . '/Module.php',
    'User\Repository\User'                 => __DIR__ . '/src/User/Repository/User.php',
    'User\View\RedirectionStrategy'        => __DIR__ . '/src/User/View/RedirectionStrategy.php',
);
