<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Controller\DevelopmentModeController'        => __DIR__ . '/src/Application/Controller/DevelopmentModeController.php',
    'Application\Controller\IndexController'                  => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Entity\BaseEntity'                           => __DIR__ . '/src/Application/Entity/BaseEntity.php',
    'Application\Initializer\AuthorizationServiceInitializer' => __DIR__ . '/src/Application/Initializer/AuthorizationServiceInitializer.php',
    'Application\Initializer\LoggerInitializer'               => __DIR__ . '/src/Application/Initializer/LoggerInitializer.php',
    'Application\Module'                                      => __DIR__ . '/Module.php',
    'Application\Service\AuthorizationServiceAwareInterface'  => __DIR__ . '/src/Application/Service/AuthorizationServiceAwareInterface.php',
    'Application\Service\AuthorizationServiceAwareTrait'      => __DIR__ . '/src/Application/Service/AuthorizationServiceAwareTrait.php',
);
