<?php
return array(
    'router' => array(
        'routes' => array(
            'api.rest.account' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/accounts[/:account_uuid]',
                    'defaults' => array(
                        'controller' => 'Api\\V1\\Rest\\Account\\Controller',
                    ),
                ),
            ),
            'api.rest.profile' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/profiles[/:profile_uuid]',
                    'defaults' => array(
                        'controller' => 'Api\\V1\\Rest\\Profile\\Controller',
                    ),
                ),
            ),
            'api.rest.company' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/companies[/:uuid]',
                    'defaults' => array(
                        'controller' => 'Api\\V1\\Rest\\Company\\Controller',
                    ),
                ),
            ),
            'api.rest.account-company' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/accounts[/:account_uuid]/companies[/:company_uuid]',
                    'defaults' => array(
                        'controller' => 'Api\\V1\\Rest\\AccountCompany\\Controller',
                    ),
                ),
            ),
            'api.rest.company-employee' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/companies[/:company_employee_uuid]/employees',
                    'defaults' => array(
                        'controller' => 'Api\\V1\\Rest\\CompanyEmployee\\Controller',
                    ),
                ),
            ),
            'api.rest.company-partner' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/companies[/:company_partner_uuid]/partners',
                    'defaults' => array(
                        'controller' => 'Api\\V1\\Rest\\CompanyPartner\\Controller',
                    ),
                ),
            ),
            'api.rest.resource-meta' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/meta[/:resource_meta_id]',
                    'defaults' => array(
                        'controller' => 'Api\\V1\\Rest\\ResourceMeta\\Controller',
                    ),
                ),
            ),
            'api.rest.profile-status' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/profile[/:profile_uuid]/status',
                    'defaults' => array(
                        'controller' => 'Api\\V1\\Rest\\ProfileStatus\\Controller',
                    ),
                ),
            ),
            'api.rest.reference' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/ref[/:reference_group]',
                    'defaults' => array(
                        'controller' => 'Api\\V1\\Rest\\Reference\\Controller',
                    ),
                ),
            ),
            'api.rest.reference-product-group' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/ref/product-group[/:reference_code]',
                    'defaults' => array(
                        'controller' => 'Api\\V1\\Rest\\ReferenceProductGroup\\Controller',
                    ),
                ),
            ),
            'api.rest.cargo' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/cargo[/:cargo_uuid]',
                    'defaults' => array(
                        'controller' => 'Api\\V1\\Rest\\Cargo\\Controller',
                    ),
                ),
            ),
            'api.rest.ext-service' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/extservices[/:ext_service_type]',
                    'defaults' => array(
                        'controller' => 'Api\\V1\\Rest\\ExtService\\Controller',
                    ),
                ),
            ),
            'api.rest.ext-service-company' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/service/import/company[/:external_code]',
                    'defaults' => array(
                        'controller' => 'Api\\V1\\Rest\\ExtServiceCompany\\Controller',
                    ),
                ),
            ),
            'api.rest.ext-service-company-intersect' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/service/import/company-intersect[/:code]',
                    'defaults' => array(
                        'controller' => 'Api\\V1\\Rest\\ExtServiceCompanyIntersect\\Controller',
                    ),
                ),
            ),
            'api.rest.external-service-place' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/service/import/place[/:external_code]',
                    'defaults' => array(
                        'controller' => 'Api\\V1\\Rest\\ExternalServicePlace\\Controller',
                    ),
                ),
            ),
            'api.rest.external-service-place-intersect' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/service/import/place-intersect[/:source][/:external_service_place_intersect_id]',
                    'defaults' => array(
                        'controller' => 'Api\\V1\\Rest\\ExternalServicePlaceIntersect\\Controller',
                    ),
                ),
            ),
        ),
    ),
    'zf-versioning' => array(
        'uri' => array(
            0 => 'api.rest.account',
            1 => 'api.rest.profile',
            2 => 'api.rest.company',
            3 => 'api.rest.account-company',
            4 => 'api.rest.company-employee',
            5 => 'api.rest.company-partner',
            6 => 'api.rest.resource-meta',
            7 => 'api.rest.profile-status',
            8 => 'api.rest.reference',
            9 => 'api.rest.reference',
            10 => 'api.rest.reference-product-group',
            11 => 'api.rest.cargo',
            12 => 'api.rest.ext-service',
            13 => 'api.rest.ext-service-company',
            14 => 'api.rest.ext-service-company-intersect',
            15 => 'api.rest.external-service-place',
            16 => 'api.rest.external-service-place-intersect',
        ),
    ),
    'service_manager' => array(
        'invokables' => array(),
        'factories' => array(
            'AuthTokenModel' => 'AuthToken\ModelFactory',
            'QueryBuilderModel' => 'QueryBuilder\Factory\QueryBuilderModelFactory',
            'CompanyModel' => 'Account\Factory\CompanyModelFactory',
            'CompanyUserModel' => 'Account\Factory\CompanyUserModelFactory',
            'AccountModel' => 'Account\Factory\AccountModelFactory',
            'CargoModel' => 'Cargo\Factory\CargoModelFactory',
            'AddListProductGroupModel' => 'Reference\Factory\AddListProductGroupModelFactory',
            'ReferenceModel' => 'Reference\Factory\ReferenceModelFactory',
            'ExternalCompanyModel' => 'ExtService\Factory\ExternalCompanyModelFactory',
            'ExternalCompanyIntersectModel' => 'ExtService\Factory\ExternalCompanyIntersectModelFactory',
            'ExternalCompanyImportModel' => 'ExtService\Factory\ExternalCompanyImportModelFactory',
            'ExternalPunctModel' => 'ExtService\Factory\ExternalPunctModelFactory',
            'ExternalPunctIntersectModel' => 'ExtService\Factory\ExternalPunctIntersectModelFactory',
            'ExternalPunctImportModel' => 'ExtService\Factory\ExternalPunctImportModelFactory',
            'Api\\V1\\Rest\\Account\\AccountResource' => 'Api\\Factory\\AccountResource',
            'Api\\V1\\Rest\\ExtServiceCompanyIntersect\\ExtServiceCompanyIntersectResource' => 'Api\\Factory\\CompanyIntersectResourceFactory',
        ),
    ),
    'zf-rest' => array(
        'Api\\V1\\Rest\\Account\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\Account\\AccountResource',
            'route_name' => 'api.rest.account',
            'identifier_name' => 'account_uuid',
            'collection_name' => 'accounts',
            'resource_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'PATCH',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'PATCH',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => 'Api\\V1\\Rest\\Account\\AccountEntity',
            'collection_class' => 'Api\\V1\\Rest\\Account\\AccountCollection',
        ),
        'Api\\V1\\Rest\\Profile\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\Profile\\ProfileResource',
            'route_name' => 'api.rest.profile',
            'identifier_name' => 'profile_uuid',
            'collection_name' => 'profiles',
            'resource_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'PATCH',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'PATCH',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => 'Api\\V1\\Rest\\Profile\\ProfileEntity',
            'collection_class' => 'Api\\V1\\Rest\\Profile\\ProfileCollection',
        ),
        'Api\\V1\\Rest\\Company\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\Company\\CompanyResource',
            'route_name' => 'api.rest.company',
            'identifier_name' => 'uuid',
            'collection_name' => 'companies',
            'resource_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'PATCH',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'PATCH',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => 'Api\\V1\\Rest\\Company\\CompanyEntity',
            'collection_class' => 'Api\\V1\\Rest\\Company\\CompanyCollection',
        ),
        'Api\\V1\\Rest\\AccountCompany\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\AccountCompany\\AccountCompanyResource',
            'route_name' => 'api.rest.account-company',
            'identifier_name' => 'company_uuid',
            'collection_name' => 'companies',
            'resource_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'PATCH',
                4 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'PATCH',
                4 => 'DELETE',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => 'Api\\V1\\Rest\\AccountCompany\\AccountCompanyEntity',
            'collection_class' => 'Api\\V1\\Rest\\AccountCompany\\AccountCompanyCollection',
        ),
        'Api\\V1\\Rest\\CompanyEmployee\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\CompanyEmployee\\CompanyEmployeeResource',
            'route_name' => 'api.rest.company-employee',
            'identifier_name' => 'company_employee_uuid',
            'collection_name' => 'company_employee',
            'resource_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'PATCH',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'PATCH',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => 'Api\\V1\\Rest\\CompanyEmployee\\CompanyEmployeeEntity',
            'collection_class' => 'Api\\V1\\Rest\\CompanyEmployee\\CompanyEmployeeCollection',
        ),
        'Api\\V1\\Rest\\CompanyPartner\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\CompanyPartner\\CompanyPartnerResource',
            'route_name' => 'api.rest.company-partner',
            'identifier_name' => 'company_partner_uuid',
            'collection_name' => 'company_partner',
            'resource_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'PATCH',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'PATCH',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => 'Api\\V1\\Rest\\CompanyPartner\\CompanyPartnerEntity',
            'collection_class' => 'Api\\V1\\Rest\\CompanyPartner\\CompanyPartnerCollection',
        ),
        'Api\\V1\\Rest\\ResourceMeta\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\ResourceMeta\\ResourceMetaResource',
            'route_name' => 'api.rest.resource-meta',
            'identifier_name' => 'resource_meta_id',
            'collection_name' => 'resource_meta',
            'resource_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'PATCH',
                4 => 'DELETE',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => 'Api\\V1\\Rest\\ResourceMeta\\ResourceMetaEntity',
            'collection_class' => 'Api\\V1\\Rest\\ResourceMeta\\ResourceMetaCollection',
        ),
        'Api\\V1\\Rest\\ProfileStatus\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\ProfileStatus\\ProfileStatusResource',
            'route_name' => 'api.rest.profile-status',
            'identifier_name' => 'profile_uuid',
            'collection_name' => 'profile_status',
            'resource_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'DELETE',
                3 => 'PATCH',
                4 => 'PUT',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => 'Api\\V1\\Rest\\ProfileStatus\\ProfileStatusEntity',
            'collection_class' => 'Api\\V1\\Rest\\ProfileStatus\\ProfileStatusCollection',
        ),
        'Api\\V1\\Rest\\Reference\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\Reference\\ReferenceResource',
            'route_name' => 'api.rest.reference',
            'identifier_name' => 'reference_group',
            'collection_name' => 'reference',
            'resource_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'PATCH',
                4 => 'DELETE',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => 'Api\\V1\\Rest\\Reference\\ReferenceEntity',
            'collection_class' => 'Api\\V1\\Rest\\Reference\\ReferenceCollection',
        ),
        'Api\\V1\\Rest\\ReferenceProductGroup\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\ReferenceProductGroup\\ReferenceProductGroupResource',
            'route_name' => 'api.rest.reference-product-group',
            'identifier_name' => 'reference_code',
            'collection_name' => 'reference_product_group',
            'resource_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'PATCH',
                4 => 'DELETE',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => 'Api\\V1\\Rest\\ReferenceProductGroup\\ReferenceProductGroupEntity',
            'collection_class' => 'Api\\V1\\Rest\\ReferenceProductGroup\\ReferenceProductGroupCollection',
        ),
        'Api\\V1\\Rest\\Cargo\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\Cargo\\CargoResource',
            'route_name' => 'api.rest.cargo',
            'identifier_name' => 'cargo_uuid',
            'collection_name' => 'cargo',
            'resource_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'PATCH',
                4 => 'DELETE',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => '25',
            'page_size_param' => '',
            'entity_class' => 'Api\\V1\\Rest\\Cargo\\CargoEntity',
            'collection_class' => 'Api\\V1\\Rest\\Cargo\\CargoCollection',
        ),
        'Api\\V1\\Rest\\ExtService\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\ExtService\\ExtServiceResource',
            'route_name' => 'api.rest.ext-service',
            'identifier_name' => 'ext_service_type',
            'collection_name' => 'ext_service',
            'resource_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'PATCH',
                4 => 'DELETE',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Api\\V1\\Rest\\ExtService\\ExtServiceEntity',
            'collection_class' => 'Api\\V1\\Rest\\ExtService\\ExtServiceCollection',
        ),
        'Api\\V1\\Rest\\ExtServiceCompany\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\ExtServiceCompany\\ExtServiceCompanyResource',
            'route_name' => 'api.rest.ext-service-company',
            'identifier_name' => 'external_code',
            'collection_name' => 'ext_service_company',
            'resource_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'DELETE',
                3 => 'PATCH',
                4 => 'PUT',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Api\\V1\\Rest\\ExtServiceCompany\\ExtServiceCompanyEntity',
            'collection_class' => 'Api\\V1\\Rest\\ExtServiceCompany\\ExtServiceCompanyCollection',
        ),
        'Api\\V1\\Rest\\ExtServiceCompanyIntersect\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\ExtServiceCompanyIntersect\\ExtServiceCompanyIntersectResource',
            'route_name' => 'api.rest.ext-service-company-intersect',
            'identifier_name' => 'code',
            'collection_name' => 'companies',
            'resource_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'PATCH',
                4 => 'DELETE',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Api\\V1\\Rest\\ExtServiceCompanyIntersect\\ExtServiceCompanyIntersectEntity',
            'collection_class' => 'Api\\V1\\Rest\\ExtServiceCompanyIntersect\\ExtServiceCompanyIntersectCollection',
        ),
        'Api\\V1\\Rest\\ExternalServicePlace\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\ExternalServicePlace\\ExternalServicePlaceResource',
            'route_name' => 'api.rest.external-service-place',
            'identifier_name' => 'external_service_place_id',
            'collection_name' => 'external_service_place',
            'resource_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'PATCH',
                4 => 'DELETE',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Api\\V1\\Rest\\ExternalServicePlace\\ExternalServicePlaceEntity',
            'collection_class' => 'Api\\V1\\Rest\\ExternalServicePlace\\ExternalServicePlaceCollection',
        ),
        'Api\\V1\\Rest\\ExternalServicePlaceIntersect\\Controller' => array(
            'listener' => 'Api\\V1\\Rest\\ExternalServicePlaceIntersect\\ExternalServicePlaceIntersectResource',
            'route_name' => 'api.rest.external-service-place-intersect',
            'identifier_name' => 'external_service_place_intersect_id',
            'collection_name' => 'external_service_place_intersect',
            'resource_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
                2 => 'PUT',
                3 => 'PATCH',
                4 => 'DELETE',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Api\\V1\\Rest\\ExternalServicePlaceIntersect\\ExternalServicePlaceIntersectEntity',
            'collection_class' => 'Api\\V1\\Rest\\ExternalServicePlaceIntersect\\ExternalServicePlaceIntersectCollection',
        ),
    ),
    'zf-content-negotiation' => array(
        'controllers' => array(
            'Api\\V1\\Rest\\Account\\Controller' => 'HalJson',
            'Api\\V1\\Rest\\Profile\\Controller' => 'HalJson',
            'Api\\V1\\Rest\\Company\\Controller' => 'HalJson',
            'Api\\V1\\Rest\\AccountCompany\\Controller' => 'HalJson',
            'Api\\V1\\Rest\\\\Controller' => 'HalJson',
            'Api\\V1\\Rest\\CompanyEmployee\\Controller' => 'HalJson',
            'Api\\V1\\Rest\\CompanyPartner\\Controller' => 'HalJson',
            'Api\\V1\\Rest\\ResourceMeta\\Controller' => 'HalJson',
            'Api\\V1\\Rest\\ProfileStatus\\Controller' => 'HalJson',
            'Api\\V1\\Rest\\Reference\\Controller' => 'HalJson',
            'Api\\V1\\Rest\\ReferenceProductGroup\\Controller' => 'HalJson',
            'Api\\V1\\Rest\\Cargo\\Controller' => 'HalJson',
            'Api\\V1\\Rest\\ExtService\\Controller' => 'HalJson',
            'Api\\V1\\Rest\\ExtServiceCompany\\Controller' => 'HalJson',
            'Api\\V1\\Rest\\ExtServiceCompanyIntersect\\Controller' => 'HalJson',
            'Api\\V1\\Rest\\ExternalServicePlace\\Controller' => 'HalJson',
            'Api\\V1\\Rest\\ExternalServicePlaceIntersect\\Controller' => 'HalJson',
        ),
        'accept-whitelist' => array(
            'Api\\V1\\Rest\\Account\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Api\\V1\\Rest\\Profile\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Api\\V1\\Rest\\Company\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Api\\V1\\Rest\\AccountCompany\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Api\\V1\\Rest\\CompanyEmployee\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Api\\V1\\Rest\\CompanyPartner\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
        ),
        'content-type-whitelist' => array(
            'Api\\V1\\Rest\\Account\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/json',
            ),
            'Api\\V1\\Rest\\Profile\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/json',
            ),
            'Api\\V1\\Rest\\Company\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/json',
            ),
            'Api\\V1\\Rest\\AccountCompany\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/json',
            ),
            'Api\\V1\\Rest\\CompanyEmployee\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/json',
            ),
            'Api\\V1\\Rest\\CompanyPartner\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/json',
            ),
        ),
        'accept_whitelist' => array(
            'Api\\V1\\Rest\\ResourceMeta\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Api\\V1\\Rest\\AccountCompany\\Controller' => array(
                0 => 'application/json',
                1 => 'application/*+json',
            ),
            'Api\\V1\\Rest\\ProfileStatus\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Api\\V1\\Rest\\Profile\\Controller' => array(
                0 => 'application/json',
                1 => 'application/*+json',
            ),
            'Api\\V1\\Rest\\Company\\Controller' => array(
                0 => 'application/json',
                1 => 'application/*+json',
            ),
            'Api\\V1\\Rest\\Account\\Controller' => array(
                0 => 'application/json',
                1 => 'application/*+json',
            ),
            'Api\\V1\\Rest\\Reference\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
                3 => 'application/vnd.api.v1+json',
                4 => 'application/hal+json',
                5 => 'application/json',
            ),
            'Api\\V1\\Rest\\ReferenceProductGroup\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Api\\V1\\Rest\\Cargo\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Api\\V1\\Rest\\ExtService\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Api\\V1\\Rest\\ExtServiceCompany\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Api\\V1\\Rest\\ExtServiceCompanyIntersect\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Api\\V1\\Rest\\ExternalServicePlace\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Api\\V1\\Rest\\ExternalServicePlaceIntersect\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
        ),
        'content_type_whitelist' => array(
            'Api\\V1\\Rest\\ResourceMeta\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/json',
            ),
            'Api\\V1\\Rest\\AccountCompany\\Controller' => array(
                0 => 'application/json',
            ),
            'Api\\V1\\Rest\\ProfileStatus\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/json',
            ),
            'Api\\V1\\Rest\\Profile\\Controller' => array(
                0 => 'application/json',
            ),
            'Api\\V1\\Rest\\Company\\Controller' => array(
                0 => 'application/json',
            ),
            'Api\\V1\\Rest\\Account\\Controller' => array(
                0 => 'application/json',
            ),
            'Api\\V1\\Rest\\Reference\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/json',
                2 => 'application/vnd.api.v1+json',
                3 => 'application/json',
            ),
            'Api\\V1\\Rest\\ReferenceProductGroup\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/json',
            ),
            'Api\\V1\\Rest\\Cargo\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/json',
            ),
            'Api\\V1\\Rest\\ExtService\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/json',
            ),
            'Api\\V1\\Rest\\ExtServiceCompany\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/json',
            ),
            'Api\\V1\\Rest\\ExtServiceCompanyIntersect\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/json',
            ),
            'Api\\V1\\Rest\\ExternalServicePlace\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/json',
            ),
            'Api\\V1\\Rest\\ExternalServicePlaceIntersect\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/json',
            ),
        ),
    ),
    'zf-hal' => array(
        'metadata_map' => array(
            'Api\\V1\\Rest\\Account\\AccountEntity' => array(
                'identifier_name' => 'account_uuid',
                'route_name' => 'api.rest.account',
                'hydrator' => 'Reflection',
            ),
            'Api\\V1\\Rest\\Account\\AccountCollection' => array(
                'identifier_name' => 'account_uuid',
                'route_name' => 'api.rest.account',
                'is_collection' => '1',
            ),
            'Api\\V1\\Rest\\Profile\\ProfileEntity' => array(
                'identifier_name' => 'profile_uuid',
                'route_name' => 'api.rest.profile',
                'hydrator' => 'Reflection',
            ),
            'Api\\V1\\Rest\\Profile\\ProfileCollection' => array(
                'identifier_name' => 'profile_uuid',
                'route_name' => 'api.rest.profile',
                'is_collection' => '1',
            ),
            'Api\\V1\\Rest\\Company\\CompanyEntity' => array(
                'identifier_name' => 'uuid',
                'route_name' => 'api.rest.company',
                'hydrator' => 'Reflection',
            ),
            'Api\\V1\\Rest\\Company\\CompanyCollection' => array(
                'identifier_name' => 'uuid',
                'route_name' => 'api.rest.company',
                'is_collection' => '1',
            ),
            'Api\\V1\\Rest\\AccountCompany\\AccountCompanyEntity' => array(
                'identifier_name' => 'company_uuid',
                'route_name' => 'api.rest.account-company',
                'hydrator' => 'Reflection',
            ),
            'Api\\V1\\Rest\\AccountCompany\\AccountCompanyCollection' => array(
                'identifier_name' => 'company_uuid',
                'route_name' => 'api.rest.account-company',
                'is_collection' => '1',
            ),
            'Api\\V1\\Rest\\CompanyEmployee\\CompanyEmployeeEntity' => array(
                'identifier_name' => 'company_employee_uuid',
                'route_name' => 'api.rest.company-employee',
                'hydrator' => 'Reflection',
            ),
            'Api\\V1\\Rest\\CompanyEmployee\\CompanyEmployeeCollection' => array(
                'identifier_name' => 'company_employee_uuid',
                'route_name' => 'api.rest.company-employee',
                'is_collection' => '1',
            ),
            'Api\\V1\\Rest\\CompanyPartner\\CompanyPartnerEntity' => array(
                'identifier_name' => 'company_partner_uuid',
                'route_name' => 'api.rest.company-partner',
                'hydrator' => 'Reflection',
            ),
            'Api\\V1\\Rest\\CompanyPartner\\CompanyPartnerCollection' => array(
                'identifier_name' => 'company_partner_uuid',
                'route_name' => 'api.rest.company-partner',
                'is_collection' => '1',
            ),
            'Api\\V1\\Rest\\ResourceMeta\\ResourceMetaEntity' => array(
                'identifier_name' => 'resource_meta_id',
                'route_name' => 'api.rest.resource-meta',
                'hydrator' => 'Reflection',
            ),
            'Api\\V1\\Rest\\ResourceMeta\\ResourceMetaCollection' => array(
                'identifier_name' => 'resource_meta_id',
                'route_name' => 'api.rest.resource-meta',
                'is_collection' => '1',
            ),
            'Api\\V1\\Rest\\ProfileStatus\\ProfileStatusEntity' => array(
                'identifier_name' => 'profile_uuid',
                'route_name' => 'api.rest.profile-status',
                'hydrator' => 'Reflection',
            ),
            'Api\\V1\\Rest\\ProfileStatus\\ProfileStatusCollection' => array(
                'identifier_name' => 'profile_uuid',
                'route_name' => 'api.rest.profile-status',
                'is_collection' => '1',
            ),
            'Api\\V1\\Rest\\Reference\\ReferenceEntity' => array(
                'identifier_name' => 'reference_group',
                'route_name' => 'api.rest.reference',
                'hydrator' => 'Reflection',
            ),
            'Api\\V1\\Rest\\Reference\\ReferenceCollection' => array(
                'identifier_name' => 'reference_group',
                'route_name' => 'api.rest.reference',
                'is_collection' => '1',
            ),
            'Api\\V1\\Rest\\ReferenceProductGroup\\ReferenceProductGroupEntity' => array(
                'identifier_name' => 'reference_code',
                'route_name' => 'api.rest.reference-product-group',
                'hydrator' => 'Reflection',
            ),
            'Api\\V1\\Rest\\ReferenceProductGroup\\ReferenceProductGroupCollection' => array(
                'identifier_name' => 'reference_code',
                'route_name' => 'api.rest.reference-product-group',
                'is_collection' => '1',
            ),
            'Api\\V1\\Rest\\Cargo\\CargoEntity' => array(
                'identifier_name' => 'cargo_uuid',
                'route_name' => 'api.rest.cargo',
                'hydrator' => 'Reflection',
            ),
            'Api\\V1\\Rest\\Cargo\\CargoCollection' => array(
                'identifier_name' => 'cargo_uuid',
                'route_name' => 'api.rest.cargo',
                'is_collection' => '1',
            ),
            'Api\\V1\\Rest\\ExtService\\ExtServiceEntity' => array(
                'identifier_name' => 'ext_service_type',
                'route_name' => 'api.rest.ext-service',
                'hydrator' => 'Reflection',
            ),
            'Api\\V1\\Rest\\ExtService\\ExtServiceCollection' => array(
                'identifier_name' => 'ext_service_type',
                'route_name' => 'api.rest.ext-service',
                'is_collection' => true,
            ),
            'Api\\V1\\Rest\\ExtServiceCompany\\ExtServiceCompanyEntity' => array(
                'identifier_name' => 'external_code',
                'route_name' => 'api.rest.ext-service-company',
                'hydrator' => 'Reflection',
            ),
            'Api\\V1\\Rest\\ExtServiceCompany\\ExtServiceCompanyCollection' => array(
                'identifier_name' => 'external_code',
                'route_name' => 'api.rest.ext-service-company',
                'is_collection' => true,
            ),
            'Api\\V1\\Rest\\ExtServiceCompanyIntersect\\ExtServiceCompanyIntersectEntity' => array(
                'identifier_name' => 'code',
                'route_name' => 'api.rest.ext-service-company-intersect',
                'hydrator' => 'Reflection',
            ),
            'Api\\V1\\Rest\\ExtServiceCompanyIntersect\\ExtServiceCompanyIntersectCollection' => array(
                'identifier_name' => 'code',
                'route_name' => 'api.rest.ext-service-company-intersect',
                'is_collection' => true,
            ),
            'Api\\V1\\Rest\\ExternalServicePlace\\ExternalServicePlaceEntity' => array(
                'identifier_name' => 'external_code',
                'route_name' => 'api.rest.external-service-place',
                'hydrator' => 'Reflection',
            ),
            'Api\\V1\\Rest\\ExternalServicePlace\\ExternalServicePlaceCollection' => array(
                'identifier_name' => 'external_code',
                'route_name' => 'api.rest.external-service-place',
                'is_collection' => true,
            ),
            'Api\\V1\\Rest\\ExternalServicePlaceIntersect\\ExternalServicePlaceIntersectEntity' => array(
                'identifier_name' => 'external_service_place_intersect_id',
                'route_name' => 'api.rest.external-service-place-intersect',
                'hydrator' => 'Reflection',
            ),
            'Api\\V1\\Rest\\ExternalServicePlaceIntersect\\ExternalServicePlaceIntersectCollection' => array(
                'identifier_name' => 'external_service_place_intersect_id',
                'route_name' => 'api.rest.external-service-place-intersect',
                'is_collection' => true,
            ),
        ),
    ),
);
