<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Place\Entity\Address'            => __DIR__ . '/src/Place/Entity/Address.php',
    'Place\Entity\Company'            => __DIR__ . '/src/Place/Entity/Company.php',
    'Place\Entity\Contact'            => __DIR__ . '/src/Place/Entity/Contact.php',
    'Place\Entity\PlaceEntity'        => __DIR__ . '/src/Place/Entity/PlaceEntity.php',
    'Place\Entity\User'               => __DIR__ . '/src/Place/Entity/User.php',
    'Place\Factory\PlaceModelFactory' => __DIR__ . '/src/Place/Factory/PlaceModelFactory.php',
    'Place\Model\PlaceModel'          => __DIR__ . '/src/Place/Model/PlaceModel.php',
    'Place\Module'                    => __DIR__ . '/Module.php',
    'Place\Repository\Place'          => __DIR__ . '/src/Place/Repository/Place.php',
);
