<?php
// Generated by Zend Framework 2
return array(
    'Place\Module'                    => __DIR__ . '/Module.php',
    'Place\Entity\PlaceEntity'        => __DIR__ . '/src/Place/Entity/PlaceEntity.php',
    'Place\Factory\PlaceModelFactory' => __DIR__ . '/src/Place/Factory/PlaceModelFactory.php',
    'Place\Model\PlaceModel'          => __DIR__ . '/src/Place/Model/PlaceModel.php',
);
